use sslverifier;
INSERT INTO User (name, email, status) VALUES ('marvin', 'marvin1ronal@gmail.com', 1);

INSERT INTO Cluster (name) VALUES ('UDP');
INSERT INTO Cluster (name) VALUES ('MOVISTAR-CR');
INSERT INTO Cluster (name) VALUES ('ISOFT');
INSERT INTO Cluster (name) VALUES ('LIBERTY-PA');

INSERT INTO Url(domain, clusterId) VALUES ('https://udp-portal-fb-builder.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-portal-wpb-builder.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-entrenador-api.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-entrenador-ia.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-portal-fb.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-portal-wpb.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-carrito.isoft-ste.com', 1);
INSERT INTO Url(domain, clusterId) VALUES ('https://udp-bots.isoft-ste.com', 1);


INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-numa.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-fb-builder.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-ibots.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-fb-builder.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-wpb-builder.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-iabuilder.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-entrenador.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-fb.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-wpb.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-cita.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://hurryupcr.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-miticket.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-ticket.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-cita.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://mimovistarcr.isoft-ste.com/',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-carrito.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-supervisor-social.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://miliberty.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-isocial.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-ifb.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-iwp.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-iig.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-itw.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-iwpa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-igs.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-iweb.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-itelegram.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-fb.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-wp.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-ig.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-tw.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-wpa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-gs.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-web.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-telegram.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-qa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-fb-qa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-tw-qa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://movistarcr-social-ig-qa.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://telegramcr1.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://telegramcr2.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://telegramcr3.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://telegramcr4.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://telegram-liberty.isoft-ste.com',2);
INSERT INTO Url(domain,clusterId) values ('https://b2pro.app',2);
INSERT INTO Url(domain,clusterId) values ('https://liberty-carrito.isoft-ste.com/',2);


INSERT INTO Url(domain,clusterId) VALUES('https://isoft-service-bots.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-portal-fb-builder.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-portal-wp-builder.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-portal-wpb-builder.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-entrenador-api.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-entrenador-ia.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-portal-fb.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://iservices-portal-wp.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://isoft-service-portal-wbp.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://carrito.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-carrito.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://minegocioenlinea.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://securepayment.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://securepayment-qa.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://securepaymentmalek.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://securewompipayment.isoft-ste.com/',3);
INSERT INTO Url(domain,clusterId) VALUES('https://carrito-update.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social.aldeamo.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-fb-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wp-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-ig-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-tw-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wpg-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://leads-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-telegram-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-al-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-webchat-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-outlook-aldeamo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-fb.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wp.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-ig.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-tw.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wpg.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://leads.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-telegram.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-al.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-webchat.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-outlook.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-fb-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wp-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-ig-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-tw-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-wpg-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://leads-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://social-mail-qa.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://udp-social.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://udp-social-gs.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://udp-social-fb.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://chat4business.tigo.com.gt',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-fb.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-wp.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-ig.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-tw.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-gs.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-web.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-sms.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tsm.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-social-telegram.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://telegram-interconsumo.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://telegram-fvrd.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigohn-backoffice.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://tigo-backoffice.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://webhook-tw.isoft-ste.com',3);
INSERT INTO Url(domain,clusterId) VALUES('https://auditsmm.isoft-ste.com',3);


INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-ibots.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-fb.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-fb-builder.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-iabuilder.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-wpb.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-wpb-builder.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://liberty-pa-entrenador.isoft-ste.com/',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-fb.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-ig.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-tw.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-wpa.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-gs.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-web.isoft-ste.com',4);
INSERT INTO Url(domain,clusterId) VALUES('https://libertypa-social-telegram.isoft-ste.com',4);




